server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Logs del trading bot desde Docker
  - job_name: trading-bot
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/kalmann-trading-bot'
        action: keep
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
    pipeline_stages:
      # Parsear logs JSON del bot
      - json:
          expressions:
            level: level
            module: module
            timestamp: timestamp
            message: message
            error: error
            confidence: confidence
            decision: decision
            reasoning: reasoning
      - labels:
          level:
          module:
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - output:
          source: message

  # Logs desde archivos (backup)
  - job_name: trading-bot-files
    static_configs:
      - targets:
          - localhost
        labels:
          job: trading-bot-files
          __path__: /var/log/trading-bot/*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            module: module
            timestamp: timestamp
      - labels:
          level:
          module:
