global:
  resolve_timeout: 5m
  
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 12h
  receiver: 'default-receiver'
  
  routes:
    - match:
        severity: critical
      receiver: 'critical-receiver'
      continue: true
    
    - match:
        severity: warning
      receiver: 'warning-receiver'
      continue: true

receivers:
  - name: 'default-receiver'
    # Configurar webhook, email, etc.
    # webhook_configs:
    #   - url: 'http://example.com/webhook'
    
  - name: 'critical-receiver'
    # Notificaciones críticas (Telegram, SMS, etc.)
    # webhook_configs:
    #   - url: 'http://example.com/critical-webhook'
    
  - name: 'warning-receiver'
    # Notificaciones de advertencia
    # webhook_configs:
    #   - url: 'http://example.com/warning-webhook'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']
